Models/ViewModel/login.cs
using System.ComponentModel.DataAnnotations;

namespace WebCliente.Models.ViewModel
{
    public class login
    {
        [Required(ErrorMessage = "Se requiere usuario.")]
        public string user { get; set; }
        [Required(ErrorMessage = "Se requiere password.")]
        public string pass { get; set; }

        public string respuesta { get; set; }
    }
}

Controllers/LoginController.cs
using RestSharp;
using System;
using System.Configuration;
using System.Web.Mvc;
using WebCliente.Models.ViewModel;

namespace WebCliente.Controllers
{
    public class LoginController : Controller
    {

        public ActionResult Index()
        {
            login test = new login();
            test.respuesta = "New";
            return View(test);
        }
        // GET: Login
        [HttpPost]
        public  ActionResult Index(login logi)
        {
            login resp = new login();
            try
            {   
                var client = new RestClient(ConfigurationManager.AppSettings["Endpoint_Login"]);
                var req = new RestRequest(Method.POST);
                login logReq = new login();
                logReq.user = logi.user;
                logReq.pass = logi.pass;
                req.AddJsonBody(logReq);
                var res = client.Execute(req);               

                if (res.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    resp.respuesta = "Ok";                    
                    return View(resp);
                }
                if (res.StatusCode==System.Net.HttpStatusCode.Unauthorized)
                {
                    resp.respuesta = res.Content;
                }
                
            }
            catch (Exception ex)
            {

                throw new Exception("Problemas al Conectar");
            }
            return View(resp);

        }
    }
}

Controllers/PersonaController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCliente.Models.ViewModel;

namespace WebCliente.Controllers
{
    public class PersonaController : Controller
    {
        /// <summary>
        /// Pre Carga de formulario de gestion de usuarios.
        /// </summary>
        /// <returns></returns>
        public ActionResult Ingresar()
        {
            persona persona = new persona();
            persona = fillAll();
            return View(persona);
        }
        /// <summary>
        /// Método para llamar servicio de ingresar usuarios.
        /// </summary>
        /// <param name="pers"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Ingresar(FormCollection persona)
        {
            persona RespPer = new persona();
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                
                var client = new RestClient(ConfigurationManager.AppSettings["Endpoint_PersonaN"]);
                var req = new RestRequest(Method.POST);
                persona perReq = new persona();

                perReq.Prim_Nombre = persona["Prim_Nombre"];
                perReq.Sec_Nombre = persona["Sec_Nombre"];
                perReq.Prim_Apellido = persona["Prim_Apellido"];
                perReq.Sec_Apellido = persona["Sec_Apellido"];
                perReq.TipoIdentificacion = persona["TipoIdentificacion"];
                perReq.NumeroIdentificacion = persona["NumeroIdentificacion"];
                perReq.Email = persona["Email"];
                req.AddJsonBody(perReq);
                var res = client.Execute(req);
                persona resPr = JsonConvert.DeserializeObject<persona>(res.Content);
                RespPer = fillAll();
                if (res.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    if (resPr.respuesta!= "Ingresado.")
                    {
                        RespPer.respuesta = resPr.respuesta;
                    }
                    else
                    {   
                        RespPer.respuesta = "Ok";
                    }
                    
                }
                if (res.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    RespPer.respuesta = resPr.respuesta;
                }
                return View("Ingresar", RespPer);

            }
            catch (Exception ex)
            {

                throw ex;
            }

            
        }

        /// <summary>
        /// Metodo privado para traer data de personas registradas y cargar el dropdown de tipo de documento.
        /// </summary>
        /// <returns></returns>
        private persona fillAll()
        {
            persona objPer = new persona();
            try
            {

                var client = new RestClient(ConfigurationManager.AppSettings["Endpoint_Persona"]);                
                var req = new RestRequest(Method.GET);
                var res = client.Execute(req);

                List<persona> lstPer = JsonConvert.DeserializeObject<List<persona>>(res.Content);
                objPer.lstPersona = lstPer;

                //Creo el dropdownlist quemado, por que no hay instruccion de enviarlo por base de datos.
                #region Dropdow list tipo de documento
                List<SelectListItem> ddTD = new List<SelectListItem>() {
                    new SelectListItem {
                            Text = "Seleccione...", Value = null
                        },
                        new SelectListItem {
                            Text = "Cédula de Ciudananía.", Value = "CC"
                        },
                        new SelectListItem {
                            Text = "Cédula de Extranjería.", Value = "CE"
                        },
                        new SelectListItem {                            
                            Text = "NUIP.", Value = "NUIP"
                        },
                        new SelectListItem {
                            Text = "Pasaporte.", Value = "PS"
                        },
                        new SelectListItem {
                            Text = "Permiso de Residencia.", Value = "PR"
                        },
                        new SelectListItem {
                            Text = "Tarjeta de Identidad.", Value = "TI"
                        },

                    };
                ViewBag.TipoDoc = ddTD;
                #endregion

                return objPer;

            }
            catch (Exception ex)
            {

                throw ex;
            }

            
        }

    }
}

Controllers/UsuarioController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using WebCliente.Models.ViewModel;

namespace WebCliente.Controllers
{
    public class UsuarioController : Controller
    {
        /// <summary>
        /// Pre Carga de formulario de gestion de usuarios.
        /// </summary>
        /// <returns></returns>
        public ActionResult Ingresar()
        {
            usuarios usuario = new usuarios();
            usuario = fillUsr();
            return View(usuario);
        }

        /// <summary>
        /// Método para llamar servicio de ingresar usuarios.
        /// </summary>
        /// <param name="usuario"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Ingresar(FormCollection usuario)
        {
            usuarios RespUsr = new usuarios();
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                var client = new RestClient(ConfigurationManager.AppSettings["Endpoint_UsuarioN"]);
                var req = new RestRequest(Method.POST);
                usuarios usuReq = new usuarios();

                usuReq.user = usuario["user"];
                usuReq.pass = usuario["pass"];
                
                req.AddJsonBody(usuReq);
                var res = client.Execute(req);
                usuarios resPr = JsonConvert.DeserializeObject<usuarios>(res.Content);

                RespUsr = fillUsr();
                if (res.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    if (resPr.respuesta != "Usuario Ingresado.")
                    {
                        RespUsr.respuesta = resPr.respuesta;
                    }
                    else
                    {
                        RespUsr.respuesta = "Ok"; 
                    }

                }
                if (res.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    RespUsr.respuesta = resPr.respuesta;
                }
                return View("Ingresar", RespUsr);

            }
            catch (Exception ex)
            {

                throw ex;
            }


        }

        /// <summary>
        /// Metodo privado para traer data de usuarios registrados.
        /// </summary>
        /// <returns></returns>
        private usuarios fillUsr()
        {
            usuarios objUsu = new usuarios();
            try
            {

                var client = new RestClient(ConfigurationManager.AppSettings["Endpoint_Usuario"]);
                var req = new RestRequest(Method.GET);
                var res = client.Execute(req);

                List<usuarios> lstUsu = JsonConvert.DeserializeObject<List<usuarios>>(res.Content);
                objUsu.lstUsuarios = lstUsu;
                return objUsu;

            }
            catch (Exception ex)
            {

                throw ex;
            }


        }
    }
}

Views/Login/Index.cshtml
@model WebCliente.Models.ViewModel.login
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.0.0.slim.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/Propios/propios.js"></script>
    <link href="~/Content/icons/css/all.css" rel="stylesheet">
</head>
<body class="container container-fluid">
    <br />
    <div style="height:280px;display:flex;justify-content:center">
        <div style="height:280px; margin-top:15%;margin-right:10%">
            @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { id = "frm_Logueo" }))
            {

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-3">
                            <label for="User" class="col-sm-3">Usuario</label>
                        </div>
                        <div class="col col-lg-9 input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text fas fa-user" id="basic-addon1"></span>
                            </div>
                            @Html.EditorFor(model => model.user, new { htmlAttributes = new { @class = "form-control  ", @placeholder = "Ingresa Usuario" } })
                            @Html.ValidationMessageFor(a => a.user, null, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-3">
                            <label for="User" class="col-sm-3">Password</label>
                        </div>
                        <div class="col col-lg-9 input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text fas fa-lock" id="basic-addon1"></span>
                            </div>
                            @Html.EditorFor(model => model.pass, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingresa Contraseña", type = "password" } })
                            @Html.ValidationMessageFor(a => a.pass, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                        </div>
                        <div class="col col-lg-9 input-group mb-3">
                            <button type="submit" class="btn btn-outline-info btn-block " onclick="wait()" id="btn_Ing">Ingresar</button>
                        </div>
                    </div>
                </div>

            }

            
            @try
            {
                if (@Model.respuesta == "")
                {
                    <div class="row">
                        <div class="col-3">
                        </div>
                        <div class="col-sm-9 alert alert-danger alert-dismissible fade show" role="alert" id="al_alerta">
                            <strong>Error al conectar!</strong>
                            <p>Usuario o contraseña errados</p>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="close()">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>

                }
                else if (@Model.respuesta == "Ok")

                {
                    <div class="row">
                        <div class="col-3">
                        </div>
                        <div class="col col-sm-5 input-group mb-3">
                            <a href="@Url.Action("Ingresar","Persona")" class="btn btn-outline-success btn-block">Gestionar Personas</a>
                        </div>
                        <div class="col col-sm-4 input-group mb-3">
                            <a href="@Url.Action("Ingresar","Usuario")" class="btn btn-outline-dark btn-block">Gestionar Usuarios</a>

                        </div>
                    </div>
                }

            }
            catch (Exception)
            {

                throw;
            }

        </div>
    </div>
</body>
</html>